import esbuild from "esbuild";
import { copyFileSync, mkdirSync } from "node:fs";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const copyPluginAssets = {
	name: "copy-plugin-assets",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;

			mkdirSync("dist", { recursive: true });
			copyFileSync("main.js", "dist/main.js");
			copyFileSync("manifest.json", "dist/manifest.json");
			copyFileSync("styles.css", "dist/styles.css");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
	format: "cjs",
	target: "es2022",
	minify: prod,
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPluginAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
